"""Trusted reference for DAG harness smoke; not generated by an LLM."""

import argparse
import csv
import json
from pathlib import Path


def describe(path: Path) -> tuple[list[str], int]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.reader(handle)
        columns = next(reader)
        return columns, sum(1 for _ in reader)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--train", type=Path, required=True)
    parser.add_argument("--validation", type=Path, required=True)
    parser.add_argument("--test", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    train_columns, train_rows = describe(args.train)
    validation_columns, validation_rows = describe(args.validation)
    test_columns, test_rows = describe(args.test)
    if train_columns != validation_columns or train_rows < 20000:
        raise ValueError("development schema mismatch or too few training rows")
    if "target" not in train_columns or "target" in test_columns:
        raise ValueError("invalid public target columns")
    report = {
        "train_columns": train_columns, "train_rows": train_rows,
        "validation_columns": validation_columns,
        "validation_rows": validation_rows,
        "test_columns": test_columns, "test_rows": test_rows,
    }
    args.output.write_text(json.dumps(report, sort_keys=True), encoding="utf-8")


if __name__ == "__main__":
    main()
