"""Trusted reference for DAG harness smoke; not generated by an LLM."""

import argparse
from pathlib import Path

import joblib
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier, HistGradientBoostingRegressor


def prepare(frame: pd.DataFrame, columns: list[str], mappings: dict) -> pd.DataFrame:
    result = pd.DataFrame(index=frame.index)
    for column in columns:
        if column in mappings:
            values = frame[column].fillna("__MISSING__").astype(str)
            result[column] = values.map(mappings[column]).fillna(-1).astype(float)
        else:
            result[column] = pd.to_numeric(frame[column], errors="coerce")
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--train", type=Path, required=True)
    parser.add_argument("--validation", type=Path, required=True)
    parser.add_argument("--preprocessor", type=Path, required=True)
    parser.add_argument("--output-model", type=Path, required=True)
    args = parser.parse_args()
    state = joblib.load(args.preprocessor)
    train = pd.read_csv(args.train)
    validation = pd.read_csv(args.validation)
    if list(train.columns) != list(validation.columns):
        raise ValueError("train/validation schema mismatch")
    x = prepare(train, state["columns"], state["mappings"])
    y = pd.to_numeric(train["target"], errors="raise")
    classification = set(y.unique()) <= {0, 1}
    if classification:
        model = HistGradientBoostingClassifier(max_iter=90, max_leaf_nodes=31, random_state=23)
    else:
        model = HistGradientBoostingRegressor(max_iter=90, max_leaf_nodes=31, random_state=23)
    model.fit(x, y)
    joblib.dump({**state, "model": model, "classification": classification}, args.output_model)


if __name__ == "__main__":
    main()
